services:
  postgres:
    image: postgres:14
    container_name: utxo-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: yaci_indexer
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - utxo-net

  utxo-tracker:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - utxo-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/yaci_indexer?currentSchema=utxo_tracker
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

volumes:
  pgdata:

networks:
  utxo-net:
